### ISSUE TITLE
Climbing sound

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/ropes#1]
Would add to the immersion for sure. Something like [this](http://www.freesound.org/people/jergonda/sounds/254735/). 🔈

**Comment by FaceDeer** [comment]
I've added some sound from that source, let me know if it works for you (both technically and in terms of ambience)

**Comment by tacotexmex** [comment]
They felt right but a bit long so I cut three ones out from that same source which sounds a little bit better in my opinion. See PR #2.

**Comment by FaceDeer** [comment]
Sure, sounds fine. :)

**Comment by tacotexmex** [comment]
In multiplayer, I've noticed the creak sounds are heard from quite afar. Not sure how to lower the distance in the current code myself, I figured I let you know here instead.

**Comment by FaceDeer** [comment]
The sound is called "rope_creak", the rope and rope_end nodes defined in ropeboxes.lua have it in their soundsets. Sounds are defined as a SimpleSoundSpec which can either be a string with the name of the ogg file or a table that includes the name and also a "gain" parameter to change the sound's volume. I've updated the rope_creak sound to have a gain of 0.5, so it should be half as loud now, is that good? The most recent diff, https://github.com/minetest-mods/ropes/commit/1dd9d2de75011f08cd9bab949a206dafca0d3776, should show where to fiddle with that value to adjust it further.

**Comment by tacotexmex** [comment]
Thank you for explaining the inner workings! I got confused by the SimpleSoundSpec, hadn't seen it before. I think the loudness wasn't the problem but that you could hear the sound from great distance. Going to try max_hear_distance with something between 6 and 12 when I've the time.

**Comment by FaceDeer** [comment]
I'll go with whatever parameters you think work well, I don't have a multiplayer server to test this out on easily. :)
