### ISSUE TITLE
Content-DB release is very old

### ISSUE THREAD

**Issue by Konfuz** [minetest-mods/ropes#22]
I was going to write a bug-report about global audio from the ropes but I noticed that your last release (which is probably what our server uses) was 2018-05-27 and there was steady development on this git in the meantime. Perhaps you might consider doing a new release? Looking at the code I see absolutely no reason why the sound would play globally, so you probably fixed it in the meantime.

**Comment by FaceDeer** [comment]
My apologies, a while back I did a pass of my various mods to set up the content DB to auto-update on new releases and I guess I overlooked this one. I'll do that now.
