### ISSUE TITLE
Default ladder is now a unknown node

### ISSUE THREAD

**Issue by adrido** [minetest-mods/ropes#8]
also `/giveme default:ladder_wood` ends up with a error message. 

https://github.com/minetest-mods/ropes/blob/c69b6fb0e455a465104ee8974f93f3c666e080b0/extendingladder.lua#L6

Is the removing of default:ladder_wood|steel necessary? There might be other mods that depend on it.

**Comment by FaceDeer** [comment]
The goal I was going for was to "upgrade" ladders in existing worlds with new features. The main problem I ran into was that default ladders are wallmounted and I wanted to make them facedir, which has a different set of interpretations for the param2 variable.  So simply changing the existing default:ladder definition would result in existing ladder nodes winding up with wonky orientations. I needed the nodes to have distinct names for the wallmounted<->facedir update code to know what to do to param2.

I'll take another look at how I can accomplish this. I think the best approach might be to add a set of options for whether to replace existing ladders or not, with the default being not to replace. I'm on vacation right now so don't have access to my dev computer, but I'll be home in a few days and it should be a relatively simple fix. Main complexity will probably be dealing with crating recipes in the event that both ladder types are allowed to be built in the same game.

**Comment by FaceDeer** [comment]
I've made the replacement of default ladders an option in the mod's settings that is off by default.
