### ISSUE TITLE
climbing sound is heard *everywhere* in multiplayer

### ISSUE THREAD

**Issue by thomasrudin** [minetest-mods/ropes#9]
maybe it has something to do with mono/stereo streams of the audio file..

**Comment by FaceDeer** [comment]
Huh, go figure. The API documentation says

> For positional playing of sounds, only single-channel (mono) files are
> supported. Otherwise OpenAL will play them non-positionally.

So sure enough the stereo sounds are causing the problem. and it's been like that for 2 years. Baffled nobody's reported this before. I'll mono-ize the sounds and that should fix it.

**Comment by thomasrudin** [comment]
> Baffled nobody's reported this before

Yeah, people/players get used to some quirks :smile:

**EDIT:** thx for the support
